import React from "react";

const NoteViewerPage = ({
  notes,
  uploadedFile,
  selectedSubject,
  onOpenChat,
}) => {
  if (!notes) {
    return (
      <div className="note-viewer-page">
        <div className="empty-note-state">
          <h2>No Notes Available</h2>

          <p>
            Upload a syllabus and select a
            subject to generate notes.
          </p>
        </div>
      </div>
    );
  }

  const downloadFile = (type) => {
    alert(`${type} download started`);
  };

  return (
    <div className="note-viewer-page">

      {/* Header */}
      <div className="notes-header">

        <div>
          <h1>{notes.title}</h1>

          <p>
            Generated on {notes.date}
          </p>
        </div>

        <button
          className="open-chat-btn"
          onClick={onOpenChat}
        >
          Open Tutor Chat
        </button>

      </div>

      {/* Summary Cards */}
      <div className="summary-grid">

        <div className="summary-card">
          <h3>📄 Source File</h3>

          <p>
            {uploadedFile?.name ||
              "Unknown File"}
          </p>
        </div>

        <div className="summary-card">
          <h3>📚 Subject</h3>

          <p>
            {selectedSubject?.name ||
              "Not Selected"}
          </p>
        </div>

        <div className="summary-card">
          <h3>🎯 Status</h3>

          <p>Notes Generated</p>
        </div>

      </div>

      {/* Notes Container */}
      <div className="notes-container">

        <div className="note-section">

          <h2>
            📌 Overview
          </h2>

          <p>
            {notes.overview}
          </p>

        </div>

        <div className="note-section">

          <h2>
            🔑 Key Points
          </h2>

          <ul>
            {notes.keyPoints?.map(
              (point, index) => (
                <li key={index}>
                  {point}
                </li>
              )
            )}
          </ul>

        </div>

        <div className="note-section">

          <h2>
            📖 Subject Information
          </h2>

          <div className="subject-details">

            <div>
              <strong>Code:</strong>{" "}
              {selectedSubject?.code}
            </div>

            <div>
              <strong>Semester:</strong>{" "}
              {
                selectedSubject?.semester
              }
            </div>

            <div>
              <strong>Credits:</strong>{" "}
              {
                selectedSubject?.credits
              }
            </div>

          </div>

        </div>

        <div className="note-section">

          <h2>
            📚 Units Included
          </h2>

          <div className="units-container">

            {selectedSubject?.units?.map(
              (unit, index) => (
                <span
                  key={index}
                  className="unit-badge"
                >
                  {unit}
                </span>
              )
            )}

          </div>

        </div>

      </div>

      {/* Download Actions */}
      <div className="download-section">

        <h3>
          Export Notes
        </h3>

        <div className="download-buttons">

          <button
            className="download-btn pdf"
            onClick={() =>
              downloadFile("PDF")
            }
          >
            Download PDF
          </button>

          <button
            className="download-btn docx"
            onClick={() =>
              downloadFile("DOCX")
            }
          >
            Download DOCX
          </button>

          <button
            className="download-btn txt"
            onClick={() =>
              downloadFile("TXT")
            }
          >
            Download TXT
          </button>

        </div>

      </div>

      {/* Footer */}
      <div className="notes-footer">

        <p>
          Generated by NoteAI •
          AI-Powered Learning Assistant
        </p>

      </div>

    </div>
  );
};

export default NoteViewerPage;